# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-15 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170315_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 19, 14, 51, 242921, tzinfo=utc)),
        ),
    ]
